### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by jmfayard** [Kodein-Framework/Kodein-DB#33]
Hello, I have an issue with Kodein DB 0.8.0-beta

The code is at https://github.com/LouisCAD/kotlin-libraries-playground

It works locallly on macOS but not on the CI so I'm a bit at a lost

The stacktrace is here https://scans.gradle.com/s/qztqjpf2oc23u/console-log?anchor=180

Or here https://github.com/LouisCAD/kotlin-libraries-playground/pull/103/checks?check_run_id=2658798807

**Comment by SalomonBrys** [comment]
This is due to a Java 1.8 / 1.9 compatibility issue: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/
That's because your CI runs Java 8 while your MacOS probably runs Java 11.

I'll update Kodein-DB with a fix and publish ASAP.
If you don't want to wait, you can update your CI JDK to 11.

**Comment by SalomonBrys** [comment]
0.8.1-beta is out and fixes this issue.

**Comment by jmfayard** [comment]
That works, thanks!
